language: csharp
solution: RandomThreadRoulette.sln
install:
  - nuget restore RandomThreadRoulette.sln
script:
  - xbuild /p:Configuration=Debug RandomThreadRoulette.sln
#before_install:
#  - sudo apt-get install nunit-console

#after_script:
#  - nunit-console Tests/bin/Debug/Tests.dll